name: Docker Nightly Image CI

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Name of the GitHub branch to create image off.'
        required: true
        default: 'master'
      tag:
        description: 'Name of the docker tag to create.'
        required: true
        default: 'nightly'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./docker/images/n8n
          build-args: |
            N8N_VERSION=0.119.0
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/n8n:${{ github.event.inputs.tag}}
